version: "3.10"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:djangocrm
    container_name: django_crm_app
    command: python manage.py runserver 0.0.0.0:8000
